local_backend: true

logo_url: /logo.svg

backend:
    name: "github"
    repo: personal-blogs/astros
    branch: main
    base_url: https://github-auth.vinayp.com
    automatic_deployments: false

media_folder: "public/images"
public_folder: "/images"

i18n:
    structure: "multiple_folders"
    locales: ["en", "it"]
    default_locale: "en"

collections:
- name: "settings"
  label: "Site Settings"
  files:
    - file: "src/data/navigation.json"
      label: "Main Navigation"
      name: "main_nav"
      fields:
        - label: "Navigation Links"
          name: "items"
          widget: "list"
          fields:
            - {label: "Link Text", name: "label", widget: "string", required: true}
            
            - label: "Target Page (Optional if Sub-menu Exists)"
              name: "page_link"
              widget: "relation"
              collection: "pages"
              searchFields: ["title", "slug"]
              valueField: "slug"
              displayFields: ["title"]
              filter: {field: "in_navbar", value: true}
              required: false # Parent link is optional
              
            # --- KEY CHANGE: The 'children' list itself is made NOT required ---
            - label: "Child Links (Sub-menu)"
              name: "children"
              widget: "list"
              required: false # <--- THIS makes the whole sub-menu optional!
              fields: 
                - {label: "Link Text", name: "label", widget: "string", required: true}
                - label: "Target Page"
                  name: "page_link"
                  widget: "relation"
                  collection: "pages"
                  searchFields: ["title", "slug"]
                  valueField: "slug"
                  displayFields: ["title"]
                  filter: {field: "in_navbar", value: true} 
                  required: true # Child links must have a destination
    - name: "pages"
      label: "Pages"
      folder: "src/content/pages"
      create: true
      fields:
        - {label: "Title", name: "title", widget: "string"}
        - {label: "Slug", name: "slug", widget: "string"}
        - {label: "Show in Navigation Menu", name: "in_navbar", widget: "boolean", default: true}
        - {label: "Body", name: "body", widget: "markdown"}
    - name: "posts"
      i18n: true
      label: "Blog Posts"
      folder: "src/content/blog"
      create: true
      delete: true
      fields:
          - name: "title"
            widget: "string"
            label: "Post Title"
            i18n: true
          - label: "Draft"
            name: "draft"
            widget: "boolean"
            i18n: "duplicate"
          - label: "Author"
            name: "author"
            widget: "string"
            i18n: "duplicate"
          - label: "Tags"
            name: "tags"
            widget: "list"
            i18n: true
          - label: "Image"
            name: "image"
            widget: "object"
            i18n: true
            fields:
                - { label: Source, name: src, widget: image, i18n: "duplicate" }
                - { label: Alt Text, name: alt, widget: string, i18n: true }
          - label: "Snippet"
            name: "snippet"
            widget: "text"
            i18n: true
          - label: "Publish Date"
            name: "publishDate"
            widget: "datetime"
            format: "YYYY-MM-DD HH:mm"
            i18n: "duplicate"
          - label: "Category"
            name: "category"
            widget: "select"
            options: ["Tutorials", "News", "Reviews", "Frameworks"]
            i18n: "duplicate"
          - name: "body"
            widget: "markdown"
            label: "Post Body"
            i18n: true
